weather_profile:
  outputs:
    dev:
      type: postgres
      host: postgres
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('DB_NAME') }}"
      schema: weather_api
      threads: 4
  target: dev
